on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:


name: Convert

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'util/content.yml'
          from: 'yaml'
          to: 'json'
      - name: Print yaml2xml result
        run: echo "${{ steps.yaml2xml.outputs.data }}"
