name: Update Resume
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  
jobs:
  update_cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone overleaf
        run: |
          git clone https://spencerriley620%40gmail.com:${{ secrets.overleaf }}@git.overleaf.com/5e87506aa3afa80001813f3d
          ls 5e87506aa3afa80001813f3d/  
      - name: Compile default
        uses: dante-ev/latex-action@latest
        with:
          root_file: 5e87506aa3afa80001813f3d/_default_cv.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Compile basic
        uses: dante-ev/latex-action@latest
        with:
          root_file: 5e87506aa3afa80001813f3d/_basic_cv.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Move
        run: |
          ls 5e87506aa3afa80001813f3d
          mv 5e87506aa3afa80001813f3d/_default_cv.pdf ./resume.pdf
          mv 5e87506aa3afa80001813f3d/_basic_cv.pdf ./basic_cv.pdf
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Update Resume
          add: |
            'resume.pdf'
            'basic_cv.pdf'
