name: Update Resume
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  
jobs:
  update_cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone overleaf
        run: |
          # git clone https://spencerriley%40montana.edu:${{ secrets.overleaf }}@git.overleaf.com/5e87506aa3afa80001813f3d
          git clone https://git@git.overleaf.com/5e87506aa3afa80001813f3d
          ls 5e87506aa3afa80001813f3d/  
      - name: Install TeXlive
        run:  |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
      - name: Compile 
        run: |
          cd 5e87506aa3afa80001813f3d/
          echo "Starting Default"
          pdflatex ./_default_cv.tex
          echo "Default Done"
      - name: Move
        run: |
          ls 5e87506aa3afa80001813f3d
          mv 5e87506aa3afa80001813f3d/_default_cv.pdf ./resume.pdf
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Update Resume
          add: |
            'resume.pdf'
